# -*- coding: utf-8 -*-
"""BI11-141.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kh3SWmi_1fH2p8mfwXAwzV7_Sntc1TC-
"""



"""# Ex1"""

>>> print("Hello, World!")

x = int(input())
t = x
for i in range(1, t):
  print(x, end =", ")
  x=x-1
print(1)

x = int(input())
t = x
i=1
while i <= t:
  print(x)
  x=x-1
  i=i+1

"""# Ex2"""

n = int(input())
for i in range(0, n):
  if i/2 == int(i/2):
    print(i)

"""# Ex3"""

n = int(input())
a=1
for i in range(1, n+1):
  a=a*i
print(a)

"""# Ex4"""

A = int(input())
if  5<=A and A<=10:
  print("True")
else:
  print("False")



"""# Ex5"""

n = int(input())
a=1
for i in range(1, n+1):
  a=n*i
  print(n,"x",i,"=",a)

"""# Ex6"""

a=int(input())
b=int(input())
c=int(input())
if a==b and b==c:
  print("Equilateral")
elif a+b>c and a+c>b and c+b>a and abs(a-b)<c and abs(a-c)<b and abs(b-c)<a:
  if a==b or b==c or b==c:
    print("Isosceles")
  elif a*a+b*b==c*c or a*a==b*b+c*c or a*a+c*c==b*b:
    print("Square")
  else: 
    print("Normal")

"""# Ex7"""

a=int(input())
b=int(input())
c=int(input())
if a>b and b>c:
  print(a)
elif c>b and b>a:
  print(c)
else:
  print(a)

"""# Ex8"""

a=int(input())
b=int(input())
if a==b:
  print("They are equal")
elif a<b:
  for i in range(a, b+1):
    print(i)
else:
  for i in range(b, a+1):
    print(i)

"""# Ex9

"""

n = int(input())
b=0
for i in range(0, 3):
  a=n%10
  n=int(n/10)
  b=b*10+a
a=b%10
if a==1:
  print("One hundred", end =" ")
elif a==2:
  print("Two hundred", end =" ")
elif a==3:
  print("Three hundred", end =" ")
elif a==4:
  print("Four hundred", end =" ")
elif a==5:
  print("Five hundred", end =" ")
elif a==6:
  print("Six hundred", end =" ")
elif a==7:
  print("Seven hundred", end =" ")
elif a==8:
  print("Eight hundred", end =" ")
elif a==9:
  print("Nine hundred", end =" ")
b=int(b/10)
a=b%10
if a==1:
  b=int(b/10)
  a=b%10
  if a==0:
    print("ten", end =" ")
  elif a==2:
    print("twelve", end =" ")
  elif a==3:
    print("thirteen", end =" ")
  elif a==4:
    print("fourteen", end =" ")
  elif a==5:
    print("fifteen", end =" ")
  elif a==6:
    print("sixteen", end =" ")
  elif a==7:
    print("seventeen", end =" ")
  elif a==8:
    print("eighteen", end =" ")
  elif a==9:
    print("nineteen", end =" ")
else:
  if a==0:
    print("and", end =" ")
  elif a==2:
    print("twenty", end =" ")
  elif a==3:
    print("thirty", end =" ")
  elif a==4:
    print("fourty", end =" ")
  elif a==5:
    print("fifty", end =" ")
  elif a==6:
    print("sixty", end =" ")
  elif a==7:
    print("seventy", end =" ")
  elif a==8:
    print("eighty", end =" ")
  elif a==9:
    print("ninety", end =" ")
b=int(b/10)
a=b%10
if a==1:
  print("one ", end =" ")
elif a==2:
  print("two ", end =" ")
elif a==3:
  print("three ", end =" ")
elif a==4:
  print("four ", end =" ")
elif a==5:
  print("five ", end =" ")
elif a==6:
  print("six ", end =" ")
elif a==7:
  print("seven ", end =" ")
elif a==8:
  print("eight ", end =" ")
elif a==9:
  print("nine ", end =" ")

"""# Ex10"""

str = input()

c = 0
for i in str:
      c = c+1
print("Length of the input string is:", c)
print(str.upper())
print(str.lower())
print(str[1])
str1 = str[0:2]
str2 = "IN"
str3 = str[2:10]
str4 = str1 + str2 + str3
print(str4)
if "s" in str:
    print("The string contains s")
else:
    print("No")

str = input()
str2 = str.capitalize()

print("New string:", str2)